### ISSUE TITLE
Visual Studio - build error

### ISSUE THREAD

**Issue by marksynz** [ChrisHammond/HammerFlex#13]
## How to reproduce problem:
- install HammerFlex_00.01.05_Source in DNN ( i.e. Host/Extensions )
- open CSPROJ file in visual studio
- build
- Visual Studio error indicating file hammerflex.dnn file is missing
## Workaround
- download hammerflex-master.zip from github, 
- find hammerflex.dnn file
- copy hammerflex.dnn into Portals_default\Skins\HammerFlex
- attempt build in visual studio
- builds without errors
## Proposed Solution
- not exactly sure, but the hammerflex.dnn file _is_ present in the ...install.zip and ...source.zip files that were generated by the build.

**Comment by ChrisHammond** [comment]
Closing due to age
