### ISSUE TITLE
Issue with DNN 7.3

### ISSUE THREAD

**Issue by bigtfromaz** [ChrisHammond/HammerFlex#14]
I am having an issue with the latest version 1.05.  If you install DNN 7.3 open source version and add the skin, all looks good.  Here is an image of the default home page, sans the HTML stuff they had on it.  
![capture](https://cloud.githubusercontent.com/assets/7926086/3712730/63b25380-152f-11e4-8c75-4879eca61036.PNG)

However if you refresh the page, either F5 or cntl-F5 it changes to this:

![capture2](https://cloud.githubusercontent.com/assets/7926086/3712732/acbf48da-152f-11e4-84c3-235406cc6b49.PNG)

It's a vanilla installation of DNN 7.3, with the package HammerFlex_00.01.05_Install.zip downloaded from github.com installed.

The interesting part is the "Toggle Navigation: showing up. It's obviously coming from the Main.ascx file.

The displayed URL is  http://mitillodev.me/ , hosted on the localhost IIS on Windows Server 2012 R2.

I guess the next step would be for someone else to recreate the issue in order to rule out my environment as a potential issue.

**Comment by ChrisHammond** [comment]
Closing due to age
