### ISSUE TITLE
Logo graphic doesn't resize and sub-menu items (mobile size) are covered by content below

### ISSUE THREAD

**Issue by runamuk0** [ChrisHammond/HammerFlex#18]
While using the HammerFlex 1.9 skin I noticed that it did not resize my logo graphic and part of the sub-menu items (when the screen is small like mobile) are overlapped by the content below. I found the answer and wanted to share it in hopes of getting it incorporated in a future version.

/\* HammerFlex - Make logo graphic responsive */ 
# dnn_dnnLOGO_imgLogo { max-width: 100%; }

/\* HammerFlex - Correct dropdown menu so it does not appear behind content */ 
@media (max-width:767px) { .dropdown-menu { position: static; } }

**Comment by ChrisHammond** [comment]
Closing due to age
