### ISSUE TITLE
Menu's don't expand on hover.

### ISSUE THREAD

**Issue by dazinator** [ChrisHammond/HammerFlex#19]
A menu item with children - you have to click on it to expand it - and most of the time when I click it, it navigates me to that page rather than expanding to show the children. 

Is there any way this can be fixed to get the hover event working, for non touch devices?

**Comment by ChrisHammond** [comment]
The Skin's menu is designed to be most mobile friendly, so I build all my sites with the pages that have submenu items to be clickable (disable the pages themselves).

You can enable hover with CSS


ul.nav li.dropdown:hover > ul.dropdown-menu {
    display: block;
}

**Comment by dazinator** [comment]
Thanks Chris, this sorted it.
