### ISSUE TITLE
Cannot get to a level three menu item using desktop/or mobile browser

### ISSUE THREAD

**Issue by RichardHowells** [ChrisHammond/HammerFlex#20]
I find I cannot get to a level three menu item using a desktop browser.  Not in a position to test with mobile browser.

Steps to repro.  I started with a brand new DNN 7.4.0 install.  Installed Hammerflex 0.1.09.

Add three pages Level1, Level2 (as a child of level 1), Level 3 (as a child of level 2).

Disable the pages Level1 and Level2

Navigate to the home page.  A click on the Level1 menu item reveals Level2.  A click on Level2 does nothing.  I expected it to reveal Level3.

**Comment by RichardHowells** [comment]
Now tested on a mobile browser (Android 5).  Same problem.

**Comment by ChrisHammond** [comment]
I do not have time to work on HammerFlex for a few weeks. If you come up with a fix please feel free to submit a PULL request

**Comment by RichardHowells** [comment]
I nearly have a pull request for you that fixes this issue.

I have a problem understanding how the build templates are intended to work.  I changed the file  Skins\HammerFlex\css\bootstrap.css.  I assumed that the RELEASE Build process would recreate the bootstrap.min.css.  It did not.

How is it intended to build the min version?  I can see that the actual skin references the min version.

**Comment by ChrisHammond** [comment]
It won't touch min.css, I didn't build that into the templates. You'll need to make the change in both places unfortunately.

**Comment by RichardHowells** [comment]
Do I have to touch the bootstrap.css.map file?  Is it important - if so what for?

**Comment by ChrisHammond** [comment]
No clue :D

**Comment by RichardHowells** [comment]
This SO Q http://stackoverflow.com/questions/21504611/what-are-the-map-files-used-for-in-bootstrap-3-1 suggests it's for helping debugging in some tooling that I don't use.  I will ignore it.

**Comment by RichardHowells** [comment]
Pull request submitted.  Be gentle with me - it's only the second one of these I have done.

**Comment by RichardHowells** [comment]
Any chance of a merge and release?

**Comment by ChrisHammond** [comment]
Unfortunately not for a few weeks, I'm crazy busy with paid work right now

-----------------------
Chris Hammond
http://www.christoc.com

**Comment by RichardHowells** [comment]
Given you just did a release.  Any chance of merging my pull request????

**Comment by efficiondave** [comment]
Richard, I added your change but it's still not showing sub-sub menus. Seems there would need to be a JS change as .dropdown-menu is set to display:none.

**Comment by RichardHowells** [comment]
Unless I misunderstand you; I think it works for me.  I changed both js and css.

![capture](https://cloud.githubusercontent.com/assets/6627531/8438288/c1f047f8-1f5c-11e5-84cc-bcf80e9f78bc.PNG)
