### ISSUE TITLE
Installation on DNN 7.4.2

### ISSUE THREAD

**Issue by Jerome2606** [ChrisHammond/HammerFlex#22]
Hi,

I try to install your theme on my updated DNN (07.04.02). 
I get the last package source (HammerFlex_00.01.13_Source.zip)

When I install it in Host/Extensions all the job done is:
```
StartJob	Starting Installation
Info	Deleted temporary install folder
EndJob	Installation successful.
```

If I unzip the zip all content is ok.
The type is right founded in installation (skin).

Is there something to do to install on 07.04.02 ?

**Comment by ChrisHammond** [comment]
I don't understand, are you having a problem installing it on 7.4.2? Those messages are the only messages you see after doing the install?

**Comment by Jerome2606** [comment]
Yes it just install nothing. I don t have anything new in skin folder.

**Comment by Jerome2606** [comment]
Ok so I make a simple module for test and I try to install it from Host/Extension and I have the same issue ... So it's not related to this skin module but related to my last update to 7.4.2  :(:(

**Comment by ChrisHammond** [comment]
Thanks for the follow up
