### ISSUE TITLE
Include the standard bootstrap css 

### ISSUE THREAD

**Issue by weggetor** [ChrisHammond/HammerFlex#23]
in your latest release you changed the default menu color from blue to grey. Is this by design ? I was wondering because I could not see any changes in bootstrap.css when comparing old and new one (both have grey menu). The blue in the older versions came from bootstrap.min.css .... a little bit confusing!

As you told me, you "likely just didn't copy all the proper CSS". 

It would be nice if it is possible to go to http://getbootstrap.com/customize/ , upload the config.json (that is not included in your hammerflex install package now), make some changes there (colors, fonts etc) and then export the css and replace the original one from your skin with your customized version.

This is not neccessary if your css file is the original standard one, but including a config.json is a good idea in any case!

Best, Torsten

**Comment by ChrisHammond** [comment]
Closing due to age
