### ISSUE TITLE
Make use of Javascript Library feature for Bootstrap

### ISSUE THREAD

**Issue by weggetor** [ChrisHammond/HammerFlex#24]
Hi Chris,

it would be nice if you do NOT include bootstrap into your hammerflex skin. Instead you should create a javascript library for bootstrap (see: http://www.dnnsoftware.com/community-blog/cid/155157/using-javascript-libraries-in-dnn) and add a "requires" node in your manifest or bundle your Install package together with the library package.

The reason for this is the following: A lot of components out in the wild (e.g. most Angular components) require an installed bootstrap. If this is built into the skin, the module developer has no choice to check if there is bootstrap installed on the DNN machine and has also to bundle bootstrap together with his component. And if you install the module on a system with Hammerflex skin you have 2 versions of bootstrap loaded ... not the best idea.

If you are interested I can provide a ready-made bootstrap library package.

**Comment by ChrisHammond** [comment]
Closing due to age
