### ISSUE TITLE
style sheet not being included

### ISSUE THREAD

**Issue by SamuelHadsall** [ChrisHammond/HammerFlex#25]
Hi @ChrisHammond, I am having some issues with the container.css not being included. I figured this would be added automaticlly however. When I build my project all .ascx file for containers get added to the install zip folder, which works great. However, when I go to install the package in dnn, it says it can't find the container.css even though it is included in the project and I actually added an additional line to the .target file:
<ItemGroup>
      <ContainerInclude Include="**\Containers\*.ascx*" />
      <ContainerInclude Include="**\Containers\*.css*" />
    </ItemGroup>

Any suggestions?

**Comment by ChrisHammond** [comment]
You'll want the Container.CSS file in the Containers folder, do you have it in there?

**Comment by SamuelHadsall** [comment]
Yes sir. However, it's called conatiner.css (lower case (C)). Will that make a difference? @ChrisHammond

**Comment by ChrisHammond** [comment]
Shouldn't make a difference. In the .DNN file what "path" do you have referenced for that file?

**Comment by SamuelHadsall** [comment]
I believe I am using what you originally had in there which is <basepath/>. However, I don't call out the container.css in the .dnn file though. Didn't think I needed to. That being said though, that was part of my trouble shooting. I did add it in there, but because the container.css is not being included in the root of the install.zip dnn errors out, saying it can't find the file.

**Comment by ChrisHammond** [comment]
Been a while since I've used a container.css file, but I think here's what's going on. You've got it in the containers folder, but the BUILD script pulls it into the ROOT of the ZIP file. I think you'll want to add the .DNN file reference to be something like 


`<component type="Container">
          <containerFiles>
            <containerName>HammerFlex</containerName>
            <basepath/>
            <containerFile>
              <name>Main.ascx</name>
            </containerFile>
            <containerFile>
              <name>Blank.ascx</name>
            </containerFile>
            <containerFile>
              <name>container.css</name>
            </containerFile>
          </containerFiles>
        </component>`


Case shouldn't matter

**Comment by SamuelHadsall** [comment]
That is how I had it before :) The build script is not grabbing the container.css though, only the ascx files. So adding the container.css to the .dnn file gives an error, because dnn doesn't see the stylesheet there.

**Comment by ChrisHammond** [comment]
Okay then next steps  would be to try to hardcode the reference in the skinpackage.targets file to see if it will pull in container.css into the root 

Something like
 
    <ItemGroup>
      <ContainerInclude Include="**\Containers\*.*" />
      <ContainerInclude Include="**\Containers\container.css" />
    </ItemGroup>

**Comment by SamuelHadsall** [comment]
Sorry @ChrisHammond that was a no go. It's still not pushing the conainer.css into the install zip.
![containercss](https://cloud.githubusercontent.com/assets/6413981/22791149/04f34b32-eeae-11e6-9eeb-ab1426801996.png)

**Comment by SamuelHadsall** [comment]
Hi @ChrisHammond, thanks for your quick responses on this the other day. I was actually able to resolve the issue with the container style sheet not being included. I can now reference the style sheet in the dnn file and will now install with out any errors. Here is the fix for me:

  ```
<ItemGroup>
      <ContainerCSSInclude Include="**\Containers\container.css" />
    </ItemGroup>
   <Copy SourceFiles="@(ContainerCSSInclude)" DestinationFolder="Package/" />

```

**Comment by ChrisHammond** [comment]
Closing due to age
