### ISSUE TITLE
dnn v 9.04

### ISSUE THREAD

**Issue by barnsley7** [ChrisHammond/HammerFlex#27]
Has this been tested in v 9.04?

I've just tested on v9.04.04 and it failed to install. I got the standard error when installing: 

> "_An unknown error has occured. Please check your installation zip file and try again.
Common issues with bad installation files..._"

I tried increasing the file limit in web.config (maxRequestLength) - to see if that made a difference, but it still failed to install.

**Comment by ChrisHammond** [comment]
I have it running in 9.9.1 currently, haven't tested 9.4.4 for a while, but it should work there too, I definitely had it running there for a while
