### ISSUE TITLE
Cannot install Hammerflex- Critical Error 

### ISSUE THREAD

**Issue by Avidfan** [ChrisHammond/HammerFlex#9]
A critical error has occurred. Could not find file 'E:\HostingSpaces\xxxxx\xxxxx\wwwroot\Install\Temp\cjrlr2bs\license.txt'. 

I tried several different ways of getting file to load- but to no avail. (xxx=website)
Using Installation Wizard - this fails in 7.1.1

**Comment by SplatManDK** [comment]
Same error installing skin on a fresh instance (vanilla) in Azure. Can't install due to this error.

**Comment by ChrisHammond** [comment]
Thanks SplatManDK! I was beginning to wonder what was going on, but your edit says it is working fine now using the "RELEASE" files, correct?

**Comment by SplatManDK** [comment]
Yes, that is correct. The release file installs correctly.

For the uninitiated, downloading the correct file from Git can be a little confusing. I think they need a more clear "Download latest release file" link on the project front page - a lot of users do not understand software repositories and therefore just hit the Download button on the front page (which is wrong).

**Comment by ChrisHammond** [comment]
I modified the project description to try to point people to the RELEASES tab instead of the green download button. Thanks
